package generate

import (
	"bytes"
	"embed"
	"fmt"
	"path/filepath"
	"text/template"

	"github.com/Richonn/shieldci/internal/detect"
)

//go:embed templates
var templatesFS embed.FS

type GeneratedFile struct {
	Path    string
	Content []byte
}

type TemplateData struct {
	Stack     *detect.StackConfig
	RepoOwner string
	RepoName  string
	IsNode    bool
	IsPython  bool
	IsJava    bool
	IsGo      bool
	IsRust    bool
	UseYarn   bool
	UsePnpm   bool
	UseMaven  bool
	UseGradle bool
	UsePoetry bool
}

func Generate(stack *detect.StackConfig) ([]GeneratedFile, error) {
	data := &TemplateData{
		Stack:     stack,
		RepoOwner: stack.RepoOwner,
		RepoName:  stack.RepoName,
		IsNode:    stack.Language == "node",
		IsPython:  stack.Language == "python",
		IsJava:    stack.Language == "java",
		IsGo:      stack.Language == "go",
		IsRust:    stack.Language == "rust",
		UseYarn:   stack.BuildTool == "yarn",
		UsePnpm:   stack.BuildTool == "pnpm",
		UseMaven:  stack.BuildTool == "mvn",
		UseGradle: stack.BuildTool == "gradle",
		UsePoetry: stack.BuildTool == "poetry",
	}

	var files []GeneratedFile

	f, err := render("templates/base/orchestrator.yml.tmpl", "ci.yml", data)
	if err != nil {
		return nil, err
	}
	files = append(files, f)

	f, err = render("templates/base/security.yml.tmpl", "security.yml", data)
	if err != nil {
		return nil, err
	}
	files = append(files, f)

	langLintTemplates := map[string]string{
		"node":   "templates/node/lint.yml.tmpl",
		"python": "templates/python/lint.yml.tmpl",
		"java":   "templates/java/lint.yml.tmpl",
		"go":     "templates/go/lint.yml.tmpl",
		"rust":   "templates/rust/lint.yml.tmpl",
	}
	langTestTemplates := map[string]string{
		"node":   "templates/node/test.yml.tmpl",
		"python": "templates/python/test.yml.tmpl",
		"java":   "templates/java/test.yml.tmpl",
		"go":     "templates/go/test.yml.tmpl",
		"rust":   "templates/rust/test.yml.tmpl",
	}

	if tmplPath, ok := langLintTemplates[stack.Language]; ok {
		f, err = render(tmplPath, "lint.yml", data)
		if err != nil {
			return nil, err
		}
		files = append(files, f)
	}

	if tmplPath, ok := langTestTemplates[stack.Language]; ok {
		f, err = render(tmplPath, "test.yml", data)
		if err != nil {
			return nil, err
		}
		files = append(files, f)
	}

	if stack.HasDocker {
		f, err = render("templates/docker/build-scan.yml.tmpl", "docker.yml", data)
		if err != nil {
			return nil, err
		}
		files = append(files, f)
	}

	if stack.HasK8s {
		f, err = render("templates/docker/k8s-deploy.yml.tmpl", "k8s-deploy.yml", data)
		if err != nil {
			return nil, err
		}
		files = append(files, f)
	}

	if !stack.HasSemgrep && stack.SASTTool == "semgrep" {
		f, err = render("templates/base/semgrep-example.yml.tmpl", ".semgrep/rules/example.yml", data)
		if err != nil {
			return nil, err
		}
		files = append(files, f)
	}

	return files, nil
}

func PRBody(stack *detect.StackConfig, files []GeneratedFile) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "## ShieldCI - Generated Workflow\n\n")
	fmt.Fprintf(&b, "**Detected stack:** `%s`", stack.Language)
	if stack.HasDocker {
		fmt.Fprintf(&b, " + Docker")
	}
	if stack.HasK8s {
		fmt.Fprintf(&b, " + Kubernetes")
	}
	fmt.Fprintf(&b, "\n\n### Generated files\n\n")
	for _, f := range files {
		fmt.Fprintf(&b, "- `.github/workflows/%s`\n", f.Path)
	}
	fmt.Fprintf(&b, "\n---\n*Generated by [ShieldCI](https://github.com/Richonn/ShieldCI)*\n")
	return b.String()
}

func render(tmplPath, outputName string, data *TemplateData) (GeneratedFile, error) {
	funcMap := template.FuncMap{
		"gh": func(s string) string { return "${{ " + s + " }}" },
	}

	name := filepath.Base(tmplPath)
	tmpl, err := template.New(name).Funcs(funcMap).ParseFS(templatesFS, tmplPath)
	if err != nil {
		return GeneratedFile{}, fmt.Errorf("parse template %s: %w", tmplPath, err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return GeneratedFile{}, fmt.Errorf("execute template %s: %w", tmplPath, err)
	}

	return GeneratedFile{
		Path:    outputName,
		Content: buf.Bytes(),
	}, nil
}
