name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write
  packages: write
  id-token: write
  actions: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  docker:
    needs: [lint, test]
    uses: ./.github/workflows/docker.yml

  security:
    uses: ./.github/workflows/security.yml
